export const FETCH_PROMOTIONS_REQUEST = 'FETCH_PROMOTIONS_REQUEST';
export const FETCH_PROMOTIONS_SUCCESS = 'FETCH_PROMOTIONS_SUCCESS';
export const FETCH_PROMOTIONS_FAILURE = 'FETCH_PROMOTIONS_FAILURE';

export const SET_PROMOTION_FILTER = 'SET_PROMOTION_FILTER';
export const REMOVE_PROMOTION_FILTER = 'REMOVE_PROMOTION_FILTER';

export const CREATE_PROMOTION_REQUEST = 'CREATE_PROMOTION_REQUEST';
export const CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS';
export const CREATE_PROMOTION_FAILURE = 'CREATE_PROMOTION_FAILURE';
export const UPDATE_PROMOTION_FORM = 'UPDATE_PROMOTION_FORM';
export const RESET_PROMOTION_FORM = 'RESET_PROMOTION_FORM';
